package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"

	"github.com/spf13/cobra"
	"github.com/xibodev/gflow-cli/pkg/config"
	"github.com/xibodev/gflow-cli/pkg/daemon"
	"github.com/xibodev/gflow-cli/pkg/embedded"
)

var setupCmd = &cobra.Command{
	Use:     "setup",
	Aliases: []string{"install-ext", "init"},
	Short:   "Install the Chrome extension and start the background agent",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("Setting up gflow...")
		cfg := config.LoadConfig()
		if _, err := config.LoadAuth(); err != nil {
			return fmt.Errorf("failed to initialize local credentials: %w", err)
		}
		cfg = config.LoadConfig()

		extDir, err := embedded.ExtractExtension("")
		if err != nil {
			return fmt.Errorf("failed to extract extension: %w", err)
		}
		fmt.Printf("\nChrome Extension extracted to:\n   %s\n\n", extDir)

		if err := writeBridgeConfig(extDir, cfg); err != nil {
			return fmt.Errorf("failed to write extension config: %w", err)
		}
		fmt.Println("Extension endpoint configuration updated (reload the unpacked extension in Chrome).")

		if err := daemon.EnsureRunningWithAuth(cfg.Host, cfg.Port, cfg.APIToken); err != nil {
			fmt.Printf("Notice: could not start background server automatically: %v\n", err)
		} else {
			fmt.Printf("Background agent server running on http://%s:%d\n", cfg.Host, cfg.Port)
		}

		fmt.Println()
		fmt.Println("=================================================================")
		fmt.Println("  ONE-TIME STEP TO FINISH SETUP (Takes 10 seconds):")
		fmt.Println("=================================================================")
		fmt.Println("  1. In Chrome, open:  chrome://extensions")
		fmt.Println("  2. Turn ON 'Developer mode' (toggle switch in the top-right).")
		fmt.Println("  3. Click 'Load unpacked' and select the directory:")
		fmt.Printf("     %s\n", extDir)
		fmt.Println("  4. After changing host/port or re-running setup, click Reload on the extension.")
		fmt.Println("  5. Open Google Flow: https://labs.google/fx/tools/flow")
		fmt.Println("  6. Set your Flow project for generation: DEFAULT_PROJECT=<project-id>")
		fmt.Println("=================================================================")
		fmt.Println()
		openBrowser("https://labs.google/fx/tools/flow")
		return nil
	},
}

// writeBridgeConfig stores endpoint + bridge token only in the extracted
// user-local extension. Tracked extension sources never contain credentials.
func writeBridgeConfig(extDir string, cfg *config.Config) error {
	content := fmt.Sprintf(`// Generated by 'gflow setup'. Do not commit. Reload the extension after changes.
window.GFLOW_BRIDGE_CONFIG = {
  serverBase: 'http://%s:%d',
  wsUrl: 'ws://%s:%d/ws',
  bridgeToken: '%s'
};
`, cfg.Host, cfg.Port, cfg.Host, cfg.Port, cfg.BridgeToken)
	path := filepath.Join(extDir, "bridge-config.js")
	return os.WriteFile(path, []byte(content), 0600)
}

func openBrowser(url string) {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", url)
	case "darwin":
		cmd = exec.Command("open", url)
	default:
		cmd = exec.Command("xdg-open", url)
	}
	_ = cmd.Start()
}
