/**
 * Flow Bridge (Go) — Chrome Extension Background Service Worker
 *
 * Reads endpoint configuration from bridge-config.js (generated by
 * `gflow setup` into the extracted user-local extension). Tracked sources
 * never contain credentials.
 */
try {
  importScripts('bridge-config.js');
} catch (e) {
  // Fresh checkout without setup; defaults below trigger a setup reminder.
}

const EXT_CONFIG = (typeof self !== 'undefined' && self.GFLOW_BRIDGE_CONFIG) || {};
const SERVER_BASE = EXT_CONFIG.serverBase || 'http://127.0.0.1:8001';
const WS_URL = EXT_CONFIG.wsUrl || 'ws://127.0.0.1:8001/ws';
const BRIDGE_TOKEN = EXT_CONFIG.bridgeToken || null;
const FLOW_URLS = [
  'https://flow.google.com/*',
  'https://*.flow.google.com/*',
  'https://flow.google/*',
  'https://*.flow.google/*',
  'https://labs.google/fx/tools/flow*',
  'https://labs.google/fx/*/tools/flow*',
];
const DEFAULT_FLOW_URL = 'https://flow.google.com';
// Explicit allowlist: the Google bearer token is attached only here.
const ALLOWED_API_HOSTS = new Set([
  'aisandbox-pa.googleapis.com',
  'labs.google',
  'flow.google.com',
  'flow.google',
]);

// Connection state: 'disconnected' | 'connecting' | 'ready'.
let connState = 'disconnected';
let flowKey = null;
let callbackUrl = `${SERVER_BASE}/api/ext/callback`;
let clientId = 'flow-client-1';
let ws = null;
let pollTimer = null;
let pollIntervalMs = 1000;
let httpFailures = 0;
let wsFailures = 0;
const seenCommandIds = new Set();

function setState(next) {
  connState = next;
  try {
    chrome.storage.local.set({ connState: next });
  } catch (e) {
    // ignore
  }
}

function authHeaders(extra) {
  return {
    ...(extra || {}),
    ...(BRIDGE_TOKEN ? { Authorization: `Bearer ${BRIDGE_TOKEN}` } : {}),
  };
}

// Generate or load client ID
chrome.storage.local.get(['clientId', 'flowKey'], (data) => {
  if (data.clientId) {
    clientId = data.clientId;
  } else {
    clientId = 'client_' + Math.random().toString(36).substring(2, 9);
    chrome.storage.local.set({ clientId });
  }
  if (data.flowKey) flowKey = data.flowKey;
  initConnection();
});

// ─── Token Capture via webRequest ───────────────────────────
chrome.webRequest.onBeforeSendHeaders.addListener(
  (details) => {
    if (!details?.requestHeaders?.length) return;
    const authHeader = details.requestHeaders.find(
      (h) => h.name?.toLowerCase() === 'authorization'
    );
    const value = authHeader?.value || '';
    if (!value.startsWith('Bearer ya29.')) return;

    const token = value.replace(/^Bearer\s+/i, '').trim();
    if (!token) return;

    flowKey = token;
    chrome.storage.local.set({ flowKey });

    // Notify backend (session-bound; daemon updates this session only)
    sendCallback({
      type: 'token_captured',
      session_id: clientId,
      flowKey: token,
    });
  },
  { urls: [
    'https://aisandbox-pa.googleapis.com/*',
    'https://labs.google/*',
    'https://flow.google.com/*',
    'https://*.flow.google.com/*',
    'https://flow.google/*',
    'https://*.flow.google/*',
  ] },
  ['requestHeaders', 'extraHeaders']
);

// ─── Connection Lifecycle ───────────────────────────────────
function initConnection() {
  setState('connecting');
  connectHttp();
  connectWebSocket();
}

function scheduleReconnect(delayMs) {
  setState('disconnected');
  const backoff = Math.min(30000, Math.max(1000, delayMs || 2000));
  setTimeout(() => {
    if (connState === 'disconnected') initConnection();
  }, backoff);
}

chrome.alarms.create('keepAlive', { periodInMinutes: 0.5 });
chrome.alarms.onAlarm.addListener((alarm) => {
  if (alarm.name === 'keepAlive' && connState === 'disconnected') {
    initConnection();
  }
});

// HTTP Registration and Polling
async function connectHttp() {
  if (!BRIDGE_TOKEN) {
    console.warn('[Flow Bridge] No bridge token configured. Run `gflow setup`, then reload this extension.');
    scheduleReconnect(10000);
    return;
  }
  try {
    const res = await fetch(`${SERVER_BASE}/api/ext/hello`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...authHeaders() },
      body: JSON.stringify({
        type: 'hello',
        session_id: clientId,
        clientId: clientId,
        flowKey: flowKey,
        flowKeyPresent: !!flowKey,
        extension_version: chrome.runtime.getManifest().version,
      }),
    });

    if (res.status === 401) throw new Error('unauthorized (run `gflow setup` and reload)');
    if (res.status === 404) throw new Error('unknown session; re-registering');
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    if (data.callback_url) callbackUrl = new URL(data.callback_url, SERVER_BASE).toString();
    pollIntervalMs = Math.max(250, Number(data.poll_interval_ms) || 1000);
    httpFailures = 0;
    setState('ready');
    startPolling();
  } catch (err) {
    console.warn('[Flow Bridge] HTTP connect failed:', err.message);
    httpFailures += 1;
    scheduleReconnect(Math.min(30000, 2000 * httpFailures));
  }
}

function startPolling() {
  if (pollTimer) clearTimeout(pollTimer);
  pollTimer = setTimeout(pollCommands, pollIntervalMs);
}

async function pollCommands() {
  try {
    const res = await fetch(`${SERVER_BASE}/api/ext/poll?session_id=${encodeURIComponent(clientId)}`, {
      headers: authHeaders(),
    });
    if (res.status === 401 || res.status === 404) {
      // Daemon restarted or token rotated: re-register.
      await connectHttp();
      startPolling();
      return;
    }
    if (res.ok) {
      const data = await res.json();
      const commands = data.commands || [];
      for (const cmd of commands) {
        handleCommand(cmd);
      }
      httpFailures = 0;
      if (connState !== 'ready') setState('ready');
    } else {
      throw new Error(`HTTP ${res.status}`);
    }
  } catch (err) {
    httpFailures += 1;
    if (httpFailures > 5) {
      scheduleReconnect(Math.min(30000, 2000 * httpFailures));
      return;
    }
  }
  startPolling();
}

// WebSocket Connection (low latency fallback/channel)
function connectWebSocket() {
  if (!BRIDGE_TOKEN) return;
  if (ws && (ws.readyState === WebSocket.OPEN || ws.readyState === WebSocket.CONNECTING)) {
    return;
  }
  try {
    ws = new WebSocket(WS_URL);
    ws.onopen = () => {
      ws.send(JSON.stringify({
        type: 'extension_ready',
        clientId: clientId,
        bridgeToken: BRIDGE_TOKEN,
        flowKeyPresent: !!flowKey,
      }));
      if (flowKey) {
        ws.send(JSON.stringify({
          type: 'token_captured',
          clientId: clientId,
          bridgeToken: BRIDGE_TOKEN,
          flowKey: flowKey,
        }));
      }
      wsFailures = 0;
      if (connState !== 'ready') setState('ready');
    };
    ws.onmessage = ({ data }) => {
      try {
        const cmd = JSON.parse(data);
        handleCommand(cmd);
      } catch (e) {
        console.error('[Flow Bridge] WS message parse error:', e);
      }
    };
    ws.onclose = () => {
      ws = null;
      wsFailures += 1;
      if (connState === 'ready') setState('connecting');
      setTimeout(() => {
        if (!ws) connectWebSocket();
      }, Math.min(30000, 2000 * Math.max(1, wsFailures)));
    };
    ws.onerror = () => {
      try { ws.close(); } catch (e) { /* ignore */ }
      ws = null;
    };
  } catch (e) {
    ws = null;
  }
}

// ─── Dispatch & Command Handling ────────────────────────────
async function handleCommand(cmd) {
  if (!cmd || !cmd.method || !cmd.id) return;
  if (seenCommandIds.has(cmd.id)) return; // deduplicate billable commands
  seenCommandIds.add(cmd.id);
  if (seenCommandIds.size > 1000) {
    const first = seenCommandIds.values().next().value;
    seenCommandIds.delete(first);
  }
  const { id, method, params } = cmd;

  try {
    if (method === 'api_request') {
      await handleApiRequest(id, params);
    } else if (method === 'solve_captcha') {
      const result = await solveCaptcha(id, params?.captchaAction || 'IMAGE_GENERATION');
      sendCallback({ id, result });
    } else if (method === 'get_media_url') {
      await handleGetMediaUrl(id, params);
    } else if (method === 'open_flow_tab') {
      await openFlowTab();
      sendCallback({ id, status: 200, result: { opened: true } });
    } else {
      sendCallback({ id, status: 400, error: `UNKNOWN_METHOD: ${method}` });
    }
  } catch (err) {
    sendCallback({ id, status: 500, error: err?.message || 'COMMAND_FAILED' });
  }
}

function allowedUpstreamUrl(raw) {
  let u;
  try {
    u = new URL(raw);
  } catch (e) {
    return false;
  }
  if (u.protocol !== 'https:') return false;
  const host = u.hostname.toLowerCase();
  if (ALLOWED_API_HOSTS.has(host)) return true;
  if (host.endsWith('.flow.google.com') || host.endsWith('.flow.google') || host.endsWith('.labs.google')) return true;
  return false;
}

async function handleApiRequest(id, params) {
  const { url, method = 'POST', headers = {}, body, captchaAction } = params || {};
  if (!url) {
    sendCallback({ id, status: 400, error: 'MISSING_URL' });
    return;
  }
  if (!allowedUpstreamUrl(url)) {
    sendCallback({ id, status: 400, error: 'URL_NOT_ALLOWED' });
    return;
  }

  let finalBody = body;

  // Step 1: Solve reCAPTCHA if action requested
  if (captchaAction) {
    const capRes = await solveCaptcha(id, captchaAction);
    const token = capRes?.token;
    if (!token) {
      sendCallback({
        id,
        status: 403,
        error: `CAPTCHA_FAILED: ${capRes?.error || 'No token returned'}`,
      });
      return;
    }

    if (finalBody) {
      finalBody = JSON.parse(JSON.stringify(finalBody));
      if (finalBody.clientContext?.recaptchaContext) {
        finalBody.clientContext.recaptchaContext.token = token;
      }
      if (Array.isArray(finalBody.requests)) {
        for (const req of finalBody.requests) {
          if (req.clientContext?.recaptchaContext) {
            req.clientContext.recaptchaContext.token = token;
          }
        }
      }
    }
  }

  // Step 2: Set auth headers
  const fetchHeaders = {
    'accept': '*/*',
    'content-type': 'text/plain;charset=UTF-8',
    'origin': 'https://labs.google',
    'referer': 'https://labs.google/',
    ...headers,
  };

  if (flowKey) {
    fetchHeaders['authorization'] = `Bearer ${flowKey}`;
  }

  // Step 3: Run fetch in browser session
  try {
    const res = await fetch(url, {
      method,
      headers: fetchHeaders,
      credentials: 'include',
      body: method === 'GET' ? undefined : (typeof finalBody === 'string' ? finalBody : JSON.stringify(finalBody)),
    });

    const text = await res.text();
    let data;
    try {
      data = JSON.parse(text);
    } catch {
      data = text;
    }

    sendCallback({
      id,
      status: res.status,
      data,
    });
  } catch (err) {
    sendCallback({
      id,
      status: 500,
      error: err.message || 'FETCH_ERROR',
    });
  }
}

async function handleGetMediaUrl(id, params) {
  const mediaId = params?.media_id;
  if (!mediaId) {
    sendCallback({ id, status: 400, error: 'MISSING_MEDIA_ID' });
    return;
  }
  try {
    const url = `https://labs.google/fx/api/trpc/media.getMediaUrlRedirect?name=${encodeURIComponent(mediaId)}`;
    const res = await fetch(url, { credentials: 'include', redirect: 'follow' });
    if (!res.ok) {
      sendCallback({ id, status: res.status, error: `MEDIA_URL_FAILED: HTTP ${res.status}` });
      return;
    }
    sendCallback({ id, status: res.status, result: { url: res.url } });
  } catch (err) {
    sendCallback({ id, status: 500, error: err.message });
  }
}

// ─── reCAPTCHA Helper ───────────────────────────────────────
async function solveCaptcha(requestId, pageAction) {
  const tabs = await chrome.tabs.query({ url: FLOW_URLS });

  let tab = tabs[0];
  if (!tab) {
    tab = await chrome.tabs.create({ url: DEFAULT_FLOW_URL, active: false });
    await new Promise((r) => setTimeout(r, 4000));
  }

  try {
    // Send message to content script in the Flow tab
    return await chrome.tabs.sendMessage(tab.id, {
      type: 'GET_CAPTCHA',
      requestId,
      pageAction,
    });
  } catch (err) {
    // If receiving end doesn't exist, inject content script and retry
    try {
      await chrome.scripting.executeScript({
        target: { tabId: tab.id },
        files: ['content.js'],
      });
      await new Promise((r) => setTimeout(r, 500));
      return await chrome.tabs.sendMessage(tab.id, {
        type: 'GET_CAPTCHA',
        requestId,
        pageAction,
      });
    } catch (e) {
      return { error: e.message };
    }
  }
}

async function openFlowTab() {
  const tabs = await chrome.tabs.query({ url: FLOW_URLS });
  if (tabs.length) {
    await chrome.tabs.update(tabs[0].id, { active: true });
  } else {
    await chrome.tabs.create({ url: DEFAULT_FLOW_URL, active: true });
  }
}

// ─── Send Callback to Go Agent ──────────────────────────────
async function sendCallback(msg) {
  const payload = JSON.stringify({ ...msg, session_id: clientId });
  // Try HTTP callback first; an HTTP error is NOT delivery success.
  try {
    const res = await fetch(callbackUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...authHeaders(),
      },
      body: payload,
    });
    if (res.ok) return;
    if (res.status === 401 || res.status === 404) {
      await connectHttp(); // token rotated or daemon restarted
      return;
    }
  } catch (e) {
    // fall through to WS
  }
  if (ws && ws.readyState === WebSocket.OPEN) {
    try {
      ws.send(JSON.stringify({ ...msg, session_id: clientId, clientId }));
    } catch (e) {
      console.warn('[Flow Bridge] WS callback failed:', e.message);
    }
  }
}

// ─── Popup Messaging ────────────────────────────────────────
chrome.runtime.onMessage.addListener((msg, _, reply) => {
  if (msg.type === 'GET_STATUS') {
    reply({
      connected: connState === 'ready',
      hasFlowKey: !!flowKey,
      clientId,
      state: connState,
    });
  } else if (msg.type === 'OPEN_FLOW') {
    openFlowTab().then(() => reply({ ok: true }));
    return true;
  }
});
