# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gflow < Formula
  desc "Lean CLI for Google Flow (Imagen 4 & Veo 3.1)"
  homepage "https://github.com/xibodev/gflow-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.0.0/gflow_1.0.0_darwin_amd64.tar.gz"
      sha256 "8001770352a040785924a9c6b1146d838a52ea3cf294043af11d35ba184f3273"

      define_method(:install) do
        bin.install "gflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.0.0/gflow_1.0.0_darwin_arm64.tar.gz"
      sha256 "e553a870f2648b472c08c6dea88bc1faec42da1a762a3b3d2db133298cac1f6d"

      define_method(:install) do
        bin.install "gflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.0.0/gflow_1.0.0_linux_amd64.tar.gz"
      sha256 "c4289ccc12d924063736bc6e73ad6e344a3ac1fc5817825d45b07ee7d4195f17"
      define_method(:install) do
        bin.install "gflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.0.0/gflow_1.0.0_linux_arm64.tar.gz"
      sha256 "8d60f266966edc67eb1405788372c21144463a8b30fb68005e832a2d41e2d788"
      define_method(:install) do
        bin.install "gflow"
      end
    end
  end
end
