# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gflow < Formula
  desc "Lean CLI for Google Flow (Imagen 4 & Veo 3.1)"
  homepage "https://github.com/xibodev/gflow-cli"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.2.0/gflow_1.2.0_darwin_amd64.tar.gz"
      sha256 "dd0706a23db805bccd8b18f1974a543ae4dcd1a74cba18b890d2cb00028712bd"

      define_method(:install) do
        bin.install "gflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.2.0/gflow_1.2.0_darwin_arm64.tar.gz"
      sha256 "5a89cce92ee48c3f6c88df53dfdb1e1829a7df8d6b659e261a14160286659326"

      define_method(:install) do
        bin.install "gflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.2.0/gflow_1.2.0_linux_amd64.tar.gz"
      sha256 "66ce6dcfce56cc61dac33faf5d36d044dfc8dbbdfe8cf906803417d9cbbba941"
      define_method(:install) do
        bin.install "gflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.2.0/gflow_1.2.0_linux_arm64.tar.gz"
      sha256 "dbcf38f4f1a18b2f82ba98351d98db5e86b3fc0cb3cfcb30cc22e5ff20472965"
      define_method(:install) do
        bin.install "gflow"
      end
    end
  end
end
