# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gflow < Formula
  desc "Lean CLI for Google Flow (Imagen 4 & Veo 3.1)"
  homepage "https://github.com/xibodev/gflow-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.1.0/gflow_1.1.0_darwin_amd64.tar.gz"
      sha256 "a64061a31d129ff7d7394b41d33088f4c5493ca6a5b7bd5a61ba607983b46185"

      define_method(:install) do
        bin.install "gflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.1.0/gflow_1.1.0_darwin_arm64.tar.gz"
      sha256 "3298fc5862ef3a0167f2915265c53a43b1c451345eb7c0e407e9b7ce5a36003d"

      define_method(:install) do
        bin.install "gflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.1.0/gflow_1.1.0_linux_amd64.tar.gz"
      sha256 "7820bb56bb158a5774c9e93ecb222005db2687e5cf82bfdc7f332547990ca35e"
      define_method(:install) do
        bin.install "gflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xibodev/gflow-cli/releases/download/v1.1.0/gflow_1.1.0_linux_arm64.tar.gz"
      sha256 "1cdf589a37cefddf38c398cdbbb139b95cec20db42c1baa2189dae782ce06aa4"
      define_method(:install) do
        bin.install "gflow"
      end
    end
  end
end
